version = "1.0"

[workbook]
path = "c:/Users/PC/Downloads/payments_reconciliation_automation_toml_v1.xlsx"
sheet = "Test Cases"

[source]
type = "sqlserver"
server = "localhost"
port = 1433
authentication = "windows"
trust_server_certificate = true
database = "webservice"


[target]
server = "localhost"
port = 1433
database = "PaymentRecon_Target_Local"
trust_server_certificate = true
authentication = "windows"