version = "1.0"

[workbook]
path = "C:/Users/QPros/Downloads/payments_reconciliation_automation_toml_v1.xlsx"
sheet = "Test Cases"

[source]
type = "oracle"
server = "10.230.1.196"
port = 1521
database = "mohredr"
authentication = "password"
username = "younes_qpro"
oracle_client_mode = "thick"
oracle_client_dir = "C:/oracle/instantclient_23_26"

[target]
type = "sqlserver"
server = "sql-mig-01.corp.local"
port = 1433
database = "PaymentsMigrated"
trust_server_certificate = true
authentication = "windows"
